name: Deploy to GCP Cloud Run

on:
  push:
    branches: [master]

env:
  PROJECT_ID: ancisse-medical-assistant/

  REGION: europe-west1
  REPO_NAME: docker-repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Build & Push backend Docker image
      run: |
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/med-assist-backend ./backend
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/med-assist-backend

    - name: Deploy backend to Cloud Run
      run: |
        gcloud run deploy med-assist-backend \
          --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/med-assist-backend \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated

    - name: Build & Push frontend Docker image
      run: |
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/med-assist-frontend ./frontend
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/med-assist-frontend

    - name: Deploy frontend to Cloud Run
      run: |
        gcloud run deploy med-assist-frontend \
          --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/med-assist-frontend \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated
