name: Deploy to GCP Cloud Run

on:
  push:
    branches: [master]

env:
  PROJECT_ID: your-gcp-project-id
  REGION: europe-west1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build & Push backend Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/med-assist-backend ./backend
        docker push gcr.io/$PROJECT_ID/med-assist-backend

    - name: Deploy backend to Cloud Run
      run: |
        gcloud run deploy med-assist-backend \
          --image gcr.io/$PROJECT_ID/med-assist-backend \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated

    - name: Build & Push frontend Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/med-assist-frontend ./frontend
        docker push gcr.io/$PROJECT_ID/med-assist-frontend

    - name: Deploy frontend to Cloud Run
      run: |
        gcloud run deploy med-assist-frontend \
          --image gcr.io/$PROJECT_ID/med-assist-frontend \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated

